print('<<< Desafio 004 >>>')
n = input('Digite algo: ')

print('O tipo primitivo de {} é {}'.format(n, type(n)))
print('É númerico? {}'.format(n.isnumeric()))
print('É alfabético? {}'.format(n.isalpha()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('Esta escrito em letras maiúsculas? {}'.format(n.isupper()))
print('Esta escrito em letras minúsculas? {}'.format(n.islower()))
print('Esta capitalizado? {}'.format(n.istitle()))
print('Tem somente espaços? {}'.format(n.isspace()))